# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kunal Gharate
title: Senior Android developer (Under construction)
email: kunalgharate@gmail.com
website: "https://kunalgharate.github.io"

show_downloads: true

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: kunalgharate
github_username: kunalgharate
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kunalgharate
linkedin_username: kunalgharate
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: kunalgharate
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: "https://www.itsgoingto.be"
# - title: another link
#   icon: "fab fa-twitter"
#   url: "https://google.com"

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # multiline
  Hi, my name's Kunal Gharate and I'm a senior android developer. As well as android developer I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>KOTLIN</mark> and <mark>JAVA</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Super awesome project
        link: "https://grossify.in"
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: "https://github.com/sproogen/modern-resume-theme"
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |
          I started this project as a way of learning <mark>Android</mark>, <mark>PHP</mark> and <mark>Angular</mark> and it has since grown into a fully fledged app. I have learned many skills through this and I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: The Boring Company
        link: "https://boringcompany.com"
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by digging holes and making game changing products like the *not a flamethrower*
        description: |
          Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Schedio Tech Pvt Ltd
        link: "https://schediotech.com"
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by digging holes and making game changing products like the *not a flamethrower*
        description: |
          Every company needs its networks properly administered and Schedio Tech Pvt Ltd is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Pune University
        caption: 2015 - 2018
        sub_title: MCA Engineering
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: |
          During my time at Harvard I learnt most of my key skills that I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in software development and app development some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - Chess
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
#footer_show_references: true
#references_title: References on request (Override references text)

# Build settings
#remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
