# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kunal Gharate
title: Senior Android Developer
email: kunalgharate@gmail.com
website: kunalgharate.github.io

show_downloads: true

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: kunalgharate
github_username: kunalgharate
instagram_username: kunalgharate
linkedin_username: kunalgharate
youtube_username: kunalgharate

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Hi, I'm Kunal Gharate, a Senior Android Developer passionate about building seamless, performant mobile experiences.
  
  With a strong foundation in <mark>Java</mark> and <mark>Kotlin</mark>, I specialize in Android and Flutter development, leading impactful projects that solve real-world problems.

  My work is fueled by continuous learning, a love for clean architecture, and a deep commitment to user-centric design.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: EE App - Subscription Services
        link: https://ee.co.uk
        quote: >
          A flagship app serving 25M+ customers in 60 countries, built with Flutter for EE, UK's largest subscription business.
        description: |
          * Flutter, Bloc, AutoRoute, Firebase, AEM, Dynatrace
          * Built "Add TV to Broadband" journey from scratch, launched with 0 defects
          * Integrated Apple/NowTV workflows, custom UI themes, accessibility compliance
          * Tech lead responsibilities in performance, reliability, and error monitoring

      - layout: top-middle
        title: ByTeacher - Education Intelligence
        link: https://app.byteachers.com
        quote: >
          A hybrid learning app integrating Zoom and biometric features for education.
        description: |
          * Android, Kotlin, Zoom SDK, Biometric API
          * Attendance via biometrics, live Zoom sessions, AI-driven assessments

      - layout: top-middle
        title: Health Interface
        link: https://healthinterface.com
        quote: >
          A cross-platform health ecosystem for scheduling virtual visits and managing records.
        description: |
          * Flutter, Dart, Getx, GraphQL
          * Real-time consultation, doctor search, reminders, and Vonage API integration

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Tech Mahindra Pvt Ltd
        sub_title: Sr. Software Engineer
        caption: Dec 6, 2023 - Present
      - layout: left
        title: Paptronics Pvt Ltd
        sub_title: Sr. Android Developer
        caption: Jan 2, 2023 - Sep 30, 2023
      - layout: left
        title: CoreValue Technologies Pvt Ltd
        sub_title: Mobile Development Engineer
        caption: Oct 18, 2021 - Dec 31, 2022

  - title: Education
    layout: list
    content:
      - layout: left
        title: Savitribai Phule Pune University
        caption: 2015 - 2018
        sub_title: MCA Engineering, CGPA: 8.3
      - layout: left
        title: Savitribai Phule Pune University
        caption: 2012 - 2015
        sub_title: Bachelor of Commerce, CGPA: 5.9

  - title: Skills
    layout: text
    content: |
      - Android Development: Java, Kotlin, Jetpack, MVVM, Reactive Programming
      - Flutter Development: Dart, Flutter SDK, Getx, Bloc, AutoRoute
      - Tools & APIs: Firebase, AEM, GraphQL, REST, OpenAPI, GetIt
      - Architecture: Clean Architecture, SOLID Principles, Design Patterns, Testing

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
